DROP SCHEMA IF EXISTS ubicaciones CASCADE;
CREATE SCHEMA ubicaciones;

CREATE TABLE ubicaciones.atributo_lugar (
	id serial NOT NULL,
	nombre character varying(50) NOT NULL,
	descripcion character varying(250),
	codigo_abreviacion character varying(20),
	activo boolean NOT NULL,
	numero_orden numeric(5,2),
	fecha_creacion timestamp NOT NULL,
	fecha_modificacion timestamp NOT NULL,
	CONSTRAINT pk_atributo_lugar PRIMARY KEY (id),
	CONSTRAINT uq_nombre_atributo_lugar UNIQUE (nombre)
);

COMMENT ON TABLE ubicaciones.atributo_lugar IS 'Tabla que almacena los atributos que puede tener un lugar';
COMMENT ON COLUMN ubicaciones.atributo_lugar.id IS 'Identificador unico de la tabla';
COMMENT ON COLUMN ubicaciones.atributo_lugar.nombre IS 'Indica el nombre del atributo para un lugar';
COMMENT ON COLUMN ubicaciones.atributo_lugar.descripcion IS 'Descripción opcional del atributo del lugar';
COMMENT ON COLUMN ubicaciones.atributo_lugar.codigo_abreviacion IS 'Código de abreviación, sigla, acrónimo u otra representación corta del registro si se requiere. ';
COMMENT ON COLUMN ubicaciones.atributo_lugar.activo IS 'Estado del atributo del lugar';
COMMENT ON COLUMN ubicaciones.atributo_lugar.numero_orden IS 'En dado caso que se necesite establecer un orden a los registros que no se encuentre definido por aplicación ni por BD.';
COMMENT ON COLUMN ubicaciones.atributo_lugar.fecha_creacion IS 'Fecha de creación del registro';
COMMENT ON COLUMN ubicaciones.atributo_lugar.fecha_modificacion IS 'Fecha de la útlima modificación del registro';
COMMENT ON CONSTRAINT pk_atributo_lugar ON ubicaciones.atributo_lugar  IS 'Llave primaria de la tabla';
COMMENT ON CONSTRAINT uq_nombre_atributo_lugar ON ubicaciones.atributo_lugar  IS 'Constraint unique para que el nombre de atributo_lugar no se repita';


CREATE TABLE ubicaciones.lugar (
	id serial NOT NULL,
	nombre character varying(100) NOT NULL,
	tipo_lugar_id integer NOT NULL,
	activo boolean NOT NULL,
	fecha_creacion timestamp NOT NULL,
	fecha_modificacion timestamp NOT NULL,
	CONSTRAINT pk_lugar PRIMARY KEY (id)
);

COMMENT ON TABLE ubicaciones.lugar IS 'Tabla que almacena los lugares vinculados a una ubicación de forma Jerarquica  Pais, Depto, Municipio, Ciudad, Localidades, Barrios, etc.';
COMMENT ON COLUMN ubicaciones.lugar.id IS 'Identificador unico de la tabla';
COMMENT ON COLUMN ubicaciones.lugar.nombre IS 'Corresponde al nombre del lugar';
COMMENT ON COLUMN ubicaciones.lugar.activo IS 'Campo que indica si el lugar es activo o no';
COMMENT ON COLUMN ubicaciones.lugar.fecha_creacion IS 'Fecha de creación del registro';
COMMENT ON COLUMN ubicaciones.lugar.fecha_modificacion IS 'Fecha de la última modificación del registro';
COMMENT ON CONSTRAINT pk_lugar ON ubicaciones.lugar IS 'Llave primaria de la tabla';


CREATE TABLE ubicaciones.relacion_lugares (
	id serial NOT NULL,
	lugar_padre_id integer NOT NULL,
	lugar_hijo_id integer NOT NULL,
	activo boolean NOT NULL,
	fecha_creacion timestamp NOT NULL,
	fecha_modificacion timestamp NOT NULL,
	CONSTRAINT pk_relacion_lugares PRIMARY KEY (id),
    CONSTRAINT uq_hijo_id_relacion_lugares UNIQUE (lugar_hijo_id),
	CONSTRAINT uq_hijo_id_padre_id_relacion_lugares UNIQUE (lugar_padre_id,lugar_hijo_id)
);

COMMENT ON TABLE ubicaciones.relacion_lugares IS 'Tabla que almacena la relacion Jerarquica entre los lugares';
COMMENT ON COLUMN ubicaciones.relacion_lugares.id IS 'Identificador unico de la tabla';
COMMENT ON COLUMN ubicaciones.relacion_lugares.lugar_padre_id IS 'Identificador del lugar padre';
COMMENT ON COLUMN ubicaciones.relacion_lugares.lugar_hijo_id IS 'Identificador del lugar hijo';
COMMENT ON COLUMN ubicaciones.relacion_lugares.activo IS 'Indica si la relación entre los lugares se encuentra activa';
COMMENT ON COLUMN ubicaciones.relacion_lugares.fecha_creacion IS 'Fecha de creación del registro';
COMMENT ON COLUMN ubicaciones.relacion_lugares.fecha_modificacion IS 'Fecha de la última modificación del registro';
COMMENT ON CONSTRAINT pk_relacion_lugares ON ubicaciones.relacion_lugares  IS 'Llave primaria de la tabla';
COMMENT ON CONSTRAINT uq_hijo_id_relacion_lugares ON ubicaciones.relacion_lugares  IS 'Restriccion para garantizar la jerarquía entre lugares.';
COMMENT ON CONSTRAINT uq_hijo_id_padre_id_relacion_lugares ON ubicaciones.relacion_lugares  IS 'Restriccion para que solo pueda existir una unica relacion entre un padre y un hijo';


CREATE TABLE ubicaciones.tipo_lugar (
	id serial NOT NULL,
	nombre character varying(50) NOT NULL,
	descripcion character varying(250),
	codigo_abreviacion character varying(20),
	activo boolean NOT NULL,
	numero_orden numeric(5,2),
	fecha_creacion timestamp NOT NULL,
	fecha_modificacion timestamp NOT NULL,
	CONSTRAINT pk_tipo_lugar PRIMARY KEY (id),
	CONSTRAINT uq_nombre_tipo_lugar UNIQUE (nombre)
);

COMMENT ON TABLE ubicaciones.tipo_lugar IS 'Almacena los parametros de tipo_lugar';
COMMENT ON COLUMN ubicaciones.tipo_lugar.id IS 'Identificador unico de la tabla';
COMMENT ON COLUMN ubicaciones.tipo_lugar.nombre IS 'Campo obligatorio de la tabla que indica el nombre del parametro.';
COMMENT ON COLUMN ubicaciones.tipo_lugar.descripcion IS 'Descripción opcional del parámetro.';
COMMENT ON COLUMN ubicaciones.tipo_lugar.codigo_abreviacion IS 'Código de abreviación, sigla, acrónimo u otra representación corta del registro si se requiere';
COMMENT ON COLUMN ubicaciones.tipo_lugar.activo IS 'Campo de tipo boolean que inidica si el parametro esta activo';
COMMENT ON COLUMN ubicaciones.tipo_lugar.numero_orden IS ' En dado caso que se necesite establecer un orden a los registros que no se encuentre definido por aplicación ni por BD. Allí se almacena permitiendo realizar subitems mediante la precisión.';
COMMENT ON COLUMN ubicaciones.tipo_lugar.fecha_creacion IS 'Fecha de creación del registro';
COMMENT ON COLUMN ubicaciones.tipo_lugar.fecha_modificacion IS 'Fecha de la última modificación del registro';
COMMENT ON CONSTRAINT pk_tipo_lugar ON ubicaciones.tipo_lugar  IS 'Llave primaria de la tabla';
COMMENT ON CONSTRAINT uq_nombre_tipo_lugar ON ubicaciones.tipo_lugar  IS 'Constraint unique para que el nombre de tipo_lugar no se repita';

CREATE TABLE ubicaciones.valor_atributo_lugar (
	id serial NOT NULL,
	valor character varying(150) NOT NULL,
	lugar_id integer NOT NULL,
	atributo_lugar_id integer NOT NULL,
	activo boolean NOT NULL,
	fecha_creacion timestamp NOT NULL,
	fecha_modificacion timestamp NOT NULL,
	CONSTRAINT pk_valor_atributo_lugar PRIMARY KEY (id)
);

COMMENT ON TABLE ubicaciones.valor_atributo_lugar IS 'Tabla que almacena el valor de los atributos que tiene un lugar';
COMMENT ON COLUMN ubicaciones.valor_atributo_lugar.id IS 'Identificador unico de la tabla';
COMMENT ON COLUMN ubicaciones.valor_atributo_lugar.valor IS 'Valor para el atributo del lugar';
COMMENT ON COLUMN ubicaciones.valor_atributo_lugar.activo IS 'Indica el estado del registro';
COMMENT ON COLUMN ubicaciones.valor_atributo_lugar.fecha_creacion IS 'Fecha de creación del registro';
COMMENT ON COLUMN ubicaciones.valor_atributo_lugar.fecha_modificacion IS 'Fecha de la última modificación del registro';
COMMENT ON CONSTRAINT pk_valor_atributo_lugar ON ubicaciones.valor_atributo_lugar  IS 'Llave primaria de la tabla';

--Fk
ALTER TABLE ubicaciones.lugar ADD CONSTRAINT fk_lugar_tipo_lugar FOREIGN KEY (tipo_lugar_id) REFERENCES ubicaciones.tipo_lugar (id) MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE ubicaciones.valor_atributo_lugar ADD CONSTRAINT fk_valor_atributo_lugar_atributo_lugar FOREIGN KEY (atributo_lugar_id) REFERENCES ubicaciones.atributo_lugar (id) MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE ubicaciones.valor_atributo_lugar ADD CONSTRAINT fk_valor_atributo_lugar_lugar FOREIGN KEY (lugar_id) REFERENCES ubicaciones.lugar (id) MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE ubicaciones.relacion_lugares ADD CONSTRAINT fk_lugar_hijo FOREIGN KEY (lugar_hijo_id) REFERENCES ubicaciones.lugar (id) MATCH FULL ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE ubicaciones.relacion_lugares ADD CONSTRAINT fk_lugar_padre FOREIGN KEY (lugar_padre_id) REFERENCES ubicaciones.lugar (id) MATCH FULL ON DELETE NO ACTION ON UPDATE NO ACTION;

--Rollback
ALTER TABLE ubicaciones.lugar DROP CONSTRAINT IF EXISTS fk_lugar_tipo_lugar CASCADE;
ALTER TABLE ubicaciones.valor_atributo_lugar DROP CONSTRAINT IF EXISTS fk_valor_atributo_lugar_atributo_lugar CASCADE;
ALTER TABLE ubicaciones.valor_atributo_lugar DROP CONSTRAINT IF EXISTS fk_valor_atributo_lugar_lugar CASCADE;
ALTER TABLE ubicaciones.relacion_lugares DROP CONSTRAINT IF EXISTS fk_lugar_hijo CASCADE;
ALTER TABLE ubicaciones.relacion_lugares DROP CONSTRAINT IF EXISTS fk_lugar_padre CASCADE;

--###################################################################################################################################################
--###################################################################################################################################################
--DATA

--Tabla: tipo_lugar

INSERT INTO ubicaciones.tipo_lugar (id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES 
(1, 'PAIS', 'País', 'P', TRUE, 1.00, LOCALTIMESTAMP, LOCALTIMESTAMP),
(2, 'CIUDAD', 'Ciudad', 'C', TRUE, 2.00, LOCALTIMESTAMP, LOCALTIMESTAMP),
(3, 'LOCALIDAD', 'Localidad', 'L', TRUE, 3.00, LOCALTIMESTAMP, LOCALTIMESTAMP),
(4, 'DEPARTAMENTO', 'Departamento', 'D', TRUE, 4.00, LOCALTIMESTAMP, LOCALTIMESTAMP);

--Tabla: lugar

Archivo data_lugares (Al inicio estan los cambios)


--Tabla: atributo_lugar
INSERT INTO ubicaciones.atributo_lugar (id, nombre, codigo_abreviacion, activo, fecha_creacion, fecha_modificacion) VALUES 
(1, 'CAPITAL', 'CAPITAL', TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP);


--Tabla: relacion_lugares
--Se filtro la data completa por relacion contiene
select * from ubicaciones.relacion_lugares where tipo_relacion_lugar_id = 2;
-Problemas:
id: 1496 ->> (1496,'Daikondi',4,), Por restriccion de UQ solo puede ser hijo de 1 padre:

(1286,1489,1496, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
(1288,1,1496, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),

1,'Afganistán'
1489,'Bamiyán (Bāmiyān)',1,

Solución: 	Daikondi es una de las 34 provincias de Afganistán 
			Se deja hijo de Afganistán

--Filtrando la data por relacion capital

--All Capitales 
SELECT Re.id, Re.lugar_padre_id, Re.lugar_hijo_id, Lu.nombre as Padre, Lu2.nombre as Hijo 
FROM ubicaciones.relacion_lugares as Re
INNER JOIN ubicaciones.lugar as Lu ON Re.lugar_padre_id = Lu.id
INNER JOIN ubicaciones.lugar as Lu2 ON Re.lugar_hijo_id = Lu2.id
WHERE Re.tipo_relacion_lugar_id = 1
ORDER BY 1;
--Capitales padre es Pais
SELECT Re.id, Re.lugar_padre_id, Re.lugar_hijo_id, Lu.nombre as Padre, Lu2.nombre as Hijo 
FROM ubicaciones.relacion_lugares as Re
INNER JOIN ubicaciones.lugar as Lu ON Re.lugar_padre_id = Lu.id
INNER JOIN ubicaciones.lugar as Lu2 ON Re.lugar_hijo_id = Lu2.id
WHERE Re.tipo_relacion_lugar_id = 1 and Lu.tipo_lugar_id = 1
ORDER BY 1;


--Se dejan relaciones de capitales del mundo y capitales de departamentos de Colombia

INSERT INTO ubicaciones.valor_atributo_lugar (valor, lugar_id, atributo_lugar_id, activo, fecha_creacion, fecha_modificacion) VALUES
('NO APLICA',250, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1456, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1471, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1484, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1490, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1602, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1868, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',2052, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',2949, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',4025, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',9, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',4961, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',6320, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',6957, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',7168, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',7870, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',8078, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',8442, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',8711, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',9061, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',9687, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',9700, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',9740, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',10848, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',11087, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',11108, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',11231, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',11906, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',12045, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',12581, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',12583, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',12803, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',12945, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',13136, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',13222, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',13261, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',13482, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',13836, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',14087, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',14985, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',15028, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',15050, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',15094, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',15409, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',15561, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',16023, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',16217, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',16262, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',16271, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',16432, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',16512, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',16847, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',17305, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',17318, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',17432, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',17458, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',17480, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',17593, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',17637, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',17678, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',18031, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',18189, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',18930, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',18949, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',19540, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',20030, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',20065, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',20095, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',20193, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',20255, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',20262, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',20471, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',20616, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',20805, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',21015, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',21084, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',21356, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',21374, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',23878, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',24985, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25010, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25017, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25371, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25386, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25423, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25499, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25556, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25595, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25708, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25877, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25897, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25944, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',25992, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',26037, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',26103, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',26376, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',26509, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',27161, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',27271, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',27336, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',27446, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',27633, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',27638, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',28054, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',28065, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',28211, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',28285, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',28407, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',28973, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',29031, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',29139, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',30152, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',35069, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',35598, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',35758, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',37027, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',37606, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',37642, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',37838, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',38009, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',38140, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',38815, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',38845, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',38903, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',38915, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',38939, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',39110, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',39710, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',42691, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',42781, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',45745, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',52638, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',52851, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',52867, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',52928, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',52990, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53027, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53108, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53141, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53161, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53192, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53208, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53377, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53685, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53741, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',53896, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',54208, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',54357, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',54508, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',54822, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',54888, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',54916, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55033, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55035, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55080, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55153, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55168, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55194, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55201, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55361, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55585, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55598, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55638, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55774, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55924, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',55980, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',56120, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',56366, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',56525, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',56599, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',57109, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',57243, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',57858, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',58570, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',59188, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',59640, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',60456, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',62455, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',63705, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',69610, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',95655, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',95759, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',96554, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',96631, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',96723, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',96732, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',96735, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',96754, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',97367, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',97891, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',97897, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',97913, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',98023, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',98315, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',99502, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',99536, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',104150, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',112878, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',278, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',288, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',419, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',421, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',422, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',498, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',512, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',634, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',661, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',662, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',681, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',697, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',738, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',765, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',795, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',824, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',941, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',951, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',954, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',991, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1007, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1037, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1070, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1131, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1171, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1184, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1194, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1213, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1297, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1323, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1392, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1411, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP),
('NO APLICA',1416, 1, TRUE, LOCALTIMESTAMP, LOCALTIMESTAMP);


